### ISSUE TITLE
Syntax error when using IE11

### ISSUE THREAD

**Issue by severinbeauvais** [vip30/vue-plugin-helper-decorator#1]
We have a Vue 3 project with modules written in TS that therefore required this vue-plugin-helper-decorator package in order to decorate the Vuelidate validations. Eg,
```
@Validation()
public validations (): any {
  return {
    addressLocal: required
  }
}
```

Unfortunately, our web application failed to start in IE11 (Version 11.418.18362.0, Update Version: 11.0.155). The following errors were displayed in the dev tools console:
```
SCRIPT1002: Syntax error
chunk-vendors.js (30692, 117)

HTML1506: Unexpected token.
myappname (25,3)
```

Debugging the first line points to the first line of function OnIdle():
```
return Object(vue_class_component__WEBPACK_IMPORTED_MODULE_0__["createDecorator"])((componentOptions, handler) => {
```

I'm not sure if the issue is with this package, IE11, or indeed Webpack.

NB: We are not using Babel, instead importing `core-js` and `regenerator-runtime` (per the deprecation warning at https://babeljs.io/docs/en/babel-polyfill).

**Comment by severinbeauvais** [comment]
I have discovered that IE11 doesn't understand arrow functions (ie, it's ES5 not ES6). As such, our non-Babel configuration does not provide a polyfill for arrow functions, and that is possibly the problem.

**Comment by vip30** [comment]
I removed arrow function from all of the source code. 

Can you try 0.0.12 as I didn't use ie11 in my project?
